#!/bin/sh
prb_socket=/tmp/probeably.sock

send_command() {
	echo "$1" | nc -U "$prb_socket"
}

print_help() {
	echo "Usage: probeablyctl [options] [command]"
	echo "  -h           Print this help."
	echo "  -s <socket>  Path to probeably socket."
}

flag=
cmd=
for arg in $@
do
	if [ -z "$flag" ]
	then
		[ "$arg" = "-h" ] && print_help && exit
		[ "$arg" = "-s" ] && flag="-s"
	else
		[ "$flag" = "-s" ] && prb_socket="$arg" && flag=
	fi
	cmd="$arg"
done

send_command "$cmd"
