#!/bin/sh
prb_socket=/var/run/probeably/probeably.sock

function send_command() {
	if [ "$1" != "monitor" ]
	then
		echo "Error: Unknown command '$1'"
	fi

	echo "$1" | nc -U "$prb_socket"
}

function print_help() {
	echo "Usage: probeablyctl [options] [command]"
	echo "  -h           Print this help."
	echo "  -s <socket>  Path to probeably socket."
}

flag=
cmd=
for arg in $@
do
	if [ -z "$flag" ]
	then
		[ "$arg" == "-h" ] && print_help && exit
		[ "$arg" == "-s" ] && flag="-s"
	else
		[ "$flag" == "-s" ] && prb_socket="$arg" && flag=
	fi
	cmd="$arg"
done

send_command "$cmd"
